eft:
  security:
    reptile:
      mailConfig:
        enable: true
        host: mail.eft.cn
        username: saas_helper@efreight.com.cn
        password: saas_helper.eFt20190712
        nickname: '翌飞小云'
        port: 465
        title: 爬虫告警
        to:
          - mayt@efreight.cn
          - wuting@efreight.cn
          - fuyunhui@efreight.cn
          - 1281955045@qq.com
        cc:
          - fuyuanhui@efreight.cn
        useSSL: true