server:
  port: 8901


eft:
  security:
    reptile:
      mail:
        enable: true
        host: localhost
        port: 465
        username: admin
        password: 123456
        nickname: admin123
        useSSL: true
        to: fuyuanhui@efreight.cn
        cc: fuyuanhui@efreight.cn
